name = "remix-cloudflare-workers"

workers_dev = true
main = "./build/index.js"
# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = "2023-04-20"

[site]
  bucket = "./public"
  exclude = ["*.map"]

[build]
  command = "npm run build-dev"

[env.staging.build]
  command = "npm run build"

[env.production.build]
  command = "npm run build"

# staging
[env.staging]
routes = [
	{ pattern = "remix-hono-cloudflare-staging.achamaro.work", custom_domain = true }
]
tail_consumers = [{service = "remix-cloudflare-workers-staging-tail"}]


[[r2_buckets]]
binding = "BUCKET"
bucket_name = "remix-hono-cloudflare"

[[env.staging.r2_buckets]]
binding = "BUCKET"
bucket_name = "remix-hono-cloudflare-test"

[[env.production.r2_buckets]]
binding = "BUCKET"
bucket_name = "remix-hono-cloudflare"
