name = "remix-cloudflare-workers"

workers_dev = true
main = "./build/index.js"
# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = "2023-04-20"

r2_buckets  = [
  { binding = "BUCKET", bucket_name = "remix-hono-cloudflare"},
]

[site]
  bucket = "./public"

[build]
  command = "npm run build"

[env.staging]
r2_buckets  = [
  { binding = "BUCKET", bucket_name = "remix-hono-cloudflare-test"},
]
