name: Deploy

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose an environment to deploy to: <staging|production>"
        required: true
        default: "staging"
        type: choice
        options:
          - staging
          - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    environment:
      name: production
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          secrets: |
            MAIL_FROM
            MAIL_TO
            BASIC_AUTH_USERNAME
            BASIC_AUTH_PASSWORD
            ADMIN_JWT_SECRET
            ADMIN_CREDENTIALS
            DKIM_KEY
          environment: ${{ env.ENVIRONMENT }}
        env:
          MAIL_FROM: ${{ secrets.MAIL_FROM }}
          MAIL_TO: ${{ secrets.MAIL_TO }}
          BASIC_AUTH_USERNAME: ${{ secrets.BASIC_AUTH_USERNAME }}
          BASIC_AUTH_PASSWORD: ${{ secrets.BASIC_AUTH_PASSWORD }}
          ADMIN_JWT_SECRET: ${{ secrets.ADMIN_JWT_SECRET }}
          ADMIN_CREDENTIALS: ${{ secrets.ADMIN_CREDENTIALS }}
          DKIM_KEY: ${{ secrets.DKIM_KEY }}
          ENVIRONMENT: ${{ (github.head_ref || github.ref_name) != 'main' && 'staging' || '' }}
